/*
 * WaxFlower
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Contact: keijun091221@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
)

// MainAPIController binds http requests to an api service and writes the service results to the http response
type MainAPIController struct {
	service      MainAPIServicer
	errorHandler ErrorHandler
}

// MainAPIOption for how the controller is set up.
type MainAPIOption func(*MainAPIController)

// WithMainAPIErrorHandler inject ErrorHandler into controller
func WithMainAPIErrorHandler(h ErrorHandler) MainAPIOption {
	return func(c *MainAPIController) {
		c.errorHandler = h
	}
}

// NewMainAPIController creates a default api controller
func NewMainAPIController(s MainAPIServicer, opts ...MainAPIOption) Router {
	controller := &MainAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the MainAPIController
func (c *MainAPIController) Routes() Routes {
	return Routes{
		"ReservePut": Route{
			strings.ToUpper("Put"),
			"/reserve",
			c.ReservePut,
		},
		"ResetGet": Route{
			strings.ToUpper("Get"),
			"/reset",
			c.ResetGet,
		},
		"SearchGet": Route{
			strings.ToUpper("Get"),
			"/search",
			c.SearchGet,
		},
	}
}

// ReservePut -
func (c *MainAPIController) ReservePut(w http.ResponseWriter, r *http.Request) {
	ticketReserveParam := TicketReserve{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&ticketReserveParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTicketReserveRequired(ticketReserveParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertTicketReserveConstraints(ticketReserveParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ReservePut(r.Context(), ticketReserveParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// ResetGet -
func (c *MainAPIController) ResetGet(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.ResetGet(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// SearchGet -
func (c *MainAPIController) SearchGet(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	var dateParam string
	if query.Has("date") {
		param := string(query.Get("date"))

		dateParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "date"}, nil)
		return
	}
	var secParam int32
	if query.Has("sec") {
		param, err := parseNumericParameter[int32](
			query.Get("sec"),
			WithParse[int32](parseInt32),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Err: err}, nil)
			return
		}

		secParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "sec"}, nil)
		return
	}
	result, err := c.service.SearchGet(r.Context(), dateParam, secParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
