/*
 * WaxFlower
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Contact: keijun091221@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"

	"github.com/jinzhu/copier"
	"github.com/k-jun/waxflower/model"
	"github.com/k-jun/waxflower/registry"
)

// MainAPIService is a service that implements the logic for the MainAPIServicer
// This service should implement the business logic for every endpoint for the MainAPI API.
// Include any external packages or services that will be required by this service.
type MainAPIService struct {
	db registry.IRegistry
}

// NewMainAPIService creates a default api service
func NewMainAPIService(db registry.IRegistry) MainAPIServicer {
	return &MainAPIService{db}
}

// ReservePut -
func (s *MainAPIService) ReservePut(ctx context.Context, ticketReserve TicketReserve) (ImplResponse, error) {
	t := &model.Ticket{Id: ticketReserve.TicketId, User: &model.User{Id: ticketReserve.UserId}}
	_, err := s.db.Reserve(t)
	if err != nil {
		return Response(400, nil), err
	}
	return Response(200, nil), err
}

// ResetGet -
func (s *MainAPIService) ResetGet(ctx context.Context) (ImplResponse, error) {
	err := s.db.Reset()
	if err != nil {
		return Response(500, nil), err
	}
	return Response(200, nil), err
}

// SearchGet -
func (s *MainAPIService) SearchGet(ctx context.Context, date string, sec int32) (ImplResponse, error) {
	t := &model.Ticket{Game: &model.Game{Date: date}, Seat: &model.Seat{Sec: sec}}
	mts, err := s.db.Search(t)

	ts := &[]Ticket{}
	if err != nil {
		return Response(200, ts), err
	}
	err = copier.Copy(ts, mts)
	return Response(200, ts), err
}
