/*
 * WaxFlower
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Contact: keijun091221@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Game struct {

	Id string `json:"id,omitempty"`

	Date string `json:"date,omitempty"`

	Time string `json:"time,omitempty"`
}

// AssertGameRequired checks if the required fields are not zero-ed
func AssertGameRequired(obj Game) error {
	return nil
}

// AssertGameConstraints checks if the values respects the defined constraints
func AssertGameConstraints(obj Game) error {
	return nil
}
