/*
 * WaxFlower
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Contact: keijun091221@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Game struct {

	Id string `json:"id"`

	Date string `json:"date"`

	Time string `json:"time"`
}

// AssertGameRequired checks if the required fields are not zero-ed
func AssertGameRequired(obj Game) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"date": obj.Date,
		"time": obj.Time,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGameConstraints checks if the values respects the defined constraints
func AssertGameConstraints(obj Game) error {
	return nil
}
