/*
 * WaxFlower
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Contact: keijun091221@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type BuyPutRequest struct {

	Id string `json:"id,omitempty"`

	UserId string `json:"userId,omitempty"`
}

// AssertBuyPutRequestRequired checks if the required fields are not zero-ed
func AssertBuyPutRequestRequired(obj BuyPutRequest) error {
	return nil
}

// AssertBuyPutRequestConstraints checks if the values respects the defined constraints
func AssertBuyPutRequestConstraints(obj BuyPutRequest) error {
	return nil
}
