/*
 * WaxFlower
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Contact: keijun091221@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/k-jun/waxflower/go"
)

func main() {
	log.Printf("Server started")

	userDB := openapi.NewUserDB()
	UserAPIService := openapi.NewUserAPIService(userDB)
	UserAPIController := openapi.NewUserAPIController(UserAPIService)

	router := openapi.NewRouter(UserAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
