openapi: 3.0.3
info:
  title: WaxFlower
  contact:
    email: keijun091221@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
tags:
  - name: main
    description: What is essential is usually invisible to the eye
  - name: ticket
    description: Everything about ticket
  - name: user
    description: Everything about user
  - name: game
    description: Everything about game
  - name: seat
    description: Everything about seat
paths:
  /ticket:
    post:
      tags:
        - ticket
      requestBody:
        $ref: '#/components/requestBodies/Ticket'
      responses:
        200:
          $ref: "#/components/responses/200"
        400:
          $ref: "#/components/responses/400"
        409:
          $ref: "#/components/responses/409"
  /ticket/{ticketId}:
    get:
      tags:
        - ticket
      parameters:
        - in: path
          name: ticketId
          schema:
            type: string
            format: uuid
            example: 2a024d5f-8dbf-4cf3-937c-0ec3307ba65c
          required: true
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Ticket'
        404:
          $ref: "#/components/responses/404"
    put:
      tags:
        - ticket
      parameters:
        - in: path
          name: ticketId
          schema:
            type: string
            format: uuid
            example: 630fbf83-0439-4105-82d8-6318e48db075
          required: true
      requestBody:
        $ref: '#/components/requestBodies/Ticket'
      responses:
        200:
          $ref: "#/components/responses/200"
        400:
          $ref: "#/components/responses/400"
        404:
          $ref: "#/components/responses/404"
components:
  schemas:
    Ticket:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: a79b47aa-301b-3221-a323-5e63601b9615
        place:
          type: integer
          format: int64
          example: 5000
        user:
          $ref: '#/components/schemas/User'
        game:
          $ref: '#/components/schemas/Game'
        seat:
          $ref: '#/components/schemas/Seat'
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: e241f57c-0521-3caf-82ac-c1295eb32ac8
        name:
          type: string
          format: email
          example: brandonnichols@example.net
    Game:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 94518720-e444-4b18-b6f7-34d8af654a5
        date:
          type: string
          format: date
          example: 1999-07-10
        time:
          type: string
          format: date
          example: 13:45:00
    Seat:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: db10fba1-c46e-4712-a8c7-cc0991df54f4
        gate:
          type: integer
          example: 9
        col:
          type: integer
          example: 57
        row:
          type: string
          pattern: '^[A-Z][A-Z]$'
          example: A
  requestBodies:
    Ticket:
      description: A JSON object containing ticket information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ticket'
  responses:
    200:
      description: OK
    400:
      description: Bad request
    404:
      description: Not Found
    409:
      description: Conflict
    500:
      description: Unexpected Error


