openapi: 3.0.3
info:
  title: WaxFlower
  contact:
    email: keijun091221@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
tags:
  - name: ticket
    description: Everything about ticket
  - name: user
    description: Everything about user
  - name: game
    description: Everything about game
  - name: seat
    description: Everything about seat
paths:
  /tickets:
    post:
      tags:
        - ticket
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticket'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
components:
  schemas:
    Ticket:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        place:
          type: integer
          format: int64
          example: 10
        user:
          $ref: '#/components/schemas/User'
        game:
          $ref: '#/components/schemas/Game'
        seat:
          $ref: '#/components/schemas/Seat'
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: k-jun
    Game:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        date:
          type: string
        time:
          type: string
    Seat:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        gate:
          type: integer
          example: 10
